project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from scholar.views import *
from django.conf import settings


urlpatterns = [
    # path('')
    path('admin/', admin.site.urls),
    path('', include('scholar.urls')),
    path('users/', include('users.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
# users/urls.py

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_student, name='register_student'), 
    path('registration_success/', views.registration_success, name='registration_success'), 
    path('studentLogin/', views.student_login, name='student_login'),       
    path('studentLogout/', views.student_logout, name='student_logout'),
    # path('profile/', views.profile, name='profile'),
]

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>Bootstrap Example</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
    <style>
        table, th, td {
            border: 1px solid black;
        }
    </style>
</head>
<body>

    <nav class="navbar dark p-2 bg-white shadow-lg">
        <a class="navbar-brand">Navbar</a>
        <form class="form-inline">
        {% if request.user.is_authenticated%}    
            <a href="{% url 'users:student_logout' %}" class="btn btn-success my-2 my-sm-0" type="submit"> Logout</a>
        {% else %}
            <a href="{% url 'users:student_login' %}" class="btn btn-success my-2 my-sm-0" type="submit"> Login</a>
        {% endif %}
        </form>
    </nav>

    {% block start %}
    
    {% endblock %}
</body>
</html>