project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from scholar.views import *
from django.conf import settings


urlpatterns = [
    # path('')
    path('admin/', admin.site.urls),
    path('', include('scholar.urls')),
    path('users/', include('users.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py
# users/urls.py

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_student, name='register_student'), 
    path('registration_success/', views.registration_success, name='registration_success'), 
    path('studentLogin/', views.student_login, name='student_login'),       
    path('studentLogout/', views.student_logout, name='student_logout'),
    # path('profile/', views.profile, name='profile'),
]

project/users/models.py
# from django.db import models

# # Create your models here.
# from django.db import models
# from django.contrib.auth.models import AbstractUser
# # Create your models here.

# class UserInfo(models.Model):
    
#     ##  -----General-Information----
#     domicile = models.CharField(max_length=50)
#     scholar_cat = models.CharField(max_length=50)
#     name = models.CharField(max_length=50)
#     dob = models.DateField(auto_now=False, auto_now_add=False)
#     gender = models.CharField(max_length=50)
#     religion = models.CharField(max_length=50)
#     category = models.CharField(max_length=50)
#     father_name = models.CharField(max_length=50)
#     mother_name = models.CharField(max_length=50)
#     annual_income = models.IntegerField()
#     phone_number = models.CharField(max_length=10,unique=True, null=True)
#     email = models.EmailField(max_length=254)
    
    
#     ##   ----Academic Details----
#     # current
#     enrollment_no = models.IntegerField()
#     admission_year = models.DateField(auto_now=False, auto_now_add=False)
#     course = models.CharField(max_length=50)
    
#     # Previous 12th Detail
#     roll_12 = models.IntegerField()
#     board_name_12 = models.CharField(max_length=50)
#     marks_12 = models.IntegerField()
    
#     # Previous 10th Detail
#     roll_10 = models.IntegerField()
#     board_name_10 = models.CharField(max_length=50)
#     marks_10 = models.IntegerField()

#     ##  -- Other Details --
#     disabled = models.CharField(max_length=50)
#     marital_status = models.CharField(max_length=50)
#     parents_profession = models.CharField(max_length=50)
    

# class student_regis(AbstractUser):
#     applicant_name = models.CharField(max_length=150) 
#     phone_number = models.IntegerField(unique=True)
#     email = models.EmailField(max_length=254,unique=True)
#     password = models.CharField(max_length=20)
#     user_profile_image = models.ImageField(upload_to="profile")

#     USERNAME_FIELD = 'phone_number'
#     REQUIRED_FIELDS = []



# class User(AbstractUser):
#     phone_number = models.CharField(unique = True, max_length=50)
#     is_phone_verified = models.BooleanField(default = False)
#     otp = models.CharField(max_length=6)

#     USERNAME_FIELD = 'phone_number'
#     REQUIRED_FIELDS = []
#     objects = UserManager()

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     mobile = models.CharField(max_length=20)
#     otp = models.CharField(max_length=6)
#     password = models.CharField(max_length=50)



from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager,Group

class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, user_type=None, **extra_fields):
        user = self.model(username=username, user_type=user_type, **extra_fields)
        user.set_password(password)
        print(f"Password before save: {user.password}")
        user.save(using=self._db)
        print(f"Password after save: {user.password}")
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('user_type', 4)
        return self.create_user(username, password, **extra_fields)

class CustomUser(AbstractUser):
    USERNAME_FIELD = 'username'
    USER_TYPE_CHOICES = (
        (1, 'Student'),
        (2, 'Institute'),
        (3, 'StateAuthority'),
        (4, 'superuser')
    )

    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, null=True)
    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        # Set any additional behavior before saving the user
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.username} - {self.get_user_type_display()}"


class StateAuthority(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    
    ##  -----State Authority Information----
    state_name = models.CharField(max_length=255)
    state_code = models.CharField(max_length=20, unique=True)
    # Add any other relevant fields specific to the state authority

    def __str__(self):
        return self.state_name



class Institute(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    
    ##  -----Institute Information----
    institute_name = models.CharField(max_length=255)
    institute_code = models.CharField(max_length=20, unique=True)
    # Add any other relevant fields specific to the institute

    def __str__(self):
        return self.institute_name
    

class Docs(models.Model):
    
    applicant_photo = models.ImageField(upload_to="static/user_detail/")
    domicile_certificate = models.ImageField(upload_to="static/user_detail/")
    income_certficate = models.ImageField(upload_to="static/user_detail/")
    caste_certificate = models.ImageField(upload_to="static/user_detail/")
    aadhar_card = models.ImageField(upload_to="static/user_detail/")
    bonafide = models.ImageField(upload_to="static/user_detail/")
    fee_receipt = models.ImageField(upload_to="static/user_detail/")
    passbook = models.ImageField(upload_to="static/user_detail/")
    
    
class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    
    ##  -----General Information----
    domicile = models.CharField(max_length=255)
    scholar_cat = models.CharField(max_length=255)
    dob = models.DateField(default='2000-01-01')
    gender = models.CharField(max_length=10)
    religion = models.CharField(max_length=255)
    category_caste = models.CharField(max_length=255)
    father_name = models.CharField(max_length=255)
    mother_name = models.CharField(max_length=255)
    annual_income = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    phone_number = models.CharField(max_length=15,unique=True, null=True)

    ##   ----Academic Details----
    # current
    institute = models.ForeignKey(Institute, on_delete=models.SET_NULL, null=True, blank=True)
    enrollment_no = models.CharField(max_length=20)
    admission_year = models.IntegerField(null=True, blank=True)
    course = models.CharField(max_length=255,null=True, blank=True)
    
    # Previous 12th Detail
    roll_12 = models.CharField(max_length=20)
    board_name_12 = models.CharField(max_length=255,null=True, blank=True)
    marks_12 = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    
    # Previous 10th Detail
    roll_10 = models.CharField(max_length=20, null=True, blank=True)
    board_name_10 = models.CharField(max_length=255, null=True, blank=True)
    marks_10 = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    ##  -- Other Details --
    disabled = models.BooleanField(default=False)
    marital_status = models.CharField(max_length=20, null=True, blank=True)
    parents_profession = models.CharField(max_length=255, null=True, blank=True)
    
    ## -- Bank Docs ---
    acc_number = models.CharField(max_length=50)
    ifsc_num = models.CharField(max_length=50)
    
    ## -- Attached Docs --  It will be unchanged
    # applicant_photo = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # domicile_certificate = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # income_certficate = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # caste_certificate = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # aadhar_card = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # bonafide = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # fee_receipt = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    # passbook = models.OneToOneField(Docs, on_delete = models.SET_NULL)
    
    ## -- Attached Docs --
    attached_docs = models.ForeignKey(Docs, on_delete=models.SET_NULL, null=True, blank=True)


    def __str__(self):
        return self.user.username  # Assuming 'username' is a field in AbstractUser


# Create groups during the initial migration
def create_groups(sender, **kwargs):
    Group.objects.get_or_create(name='Student')
    Group.objects.get_or_create(name='Institute')
    Group.objects.get_or_create(name='StateAuthority')



# Connect the create_groups function to the post_migrate signal
models.signals.post_migrate.connect(create_groups, sender=models)

# Disconnect the create_groups function after the initial migration
models.signals.post_migrate.disconnect(create_groups, sender=models)

project/users/forms.py
from django import forms
from .models import CustomUser, Student

class UserDocsForm(forms.ModelForm):
    ...

class CustomUserForm(forms.ModelForm):
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    class Meta:
        model = CustomUser
        fields = ['username','email', 'password', 'password2','first_name','last_name']
        widgets = {
            'password': forms.PasswordInput(),
        }
        labels = {
            'username': 'Username',
            'email': 'Email',
            'password': 'Password',
            'first_name': 'First Name',
            'last_name': 'Last Name',
        }
        required = {
            'username': True,
            'email': True,
            'password': True,
            'password2': True,
            'first_name': True,
            'last_name': True,
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError(
                "Passwords do not match"
            )
        
    

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['enrollment_no', 'course', 'institute']
        labels = {
            'enrollment_no': 'Enrollment Number',
            'course': 'Course',
            'institute': 'Institute/University',
        }
    

project/users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, logout
from .forms import CustomUserForm, StudentForm
from django.http import HttpResponseRedirect

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

from .models import *
# Create your views here.


from django.contrib.auth.hashers import make_password

def register_student(request):
    if request.method == 'POST':
        user_form = CustomUserForm(request.POST)
        student_form = StudentForm(request.POST)

        # Check if both forms are valid
        if user_form.is_valid() and student_form.is_valid():
            # Save the user form with user_type set to 1 for students
            user = user_form.save(commit=False)
            user.user_type = 1  # Assuming 1 represents the "Student" user type
            user.password = make_password(user_form.cleaned_data['password'])  # Manually hash the password
            user.save()

            # Save the student form with the user instance
            student = student_form.save(commit=False)
            student.user = user
            student.save()

            return HttpResponseRedirect(reverse("users:registration_success"))

    else:
        user_form = CustomUserForm()
        student_form = StudentForm()

    return render(request, 'users/register.html', {'user_form': user_form, 'student_form': student_form})



def registration_success(request):
    print('it worked')
    print(request.user)
    return render(request, 'users/registration_success.html')


def Scholar_application(request):
    if request.method == "POST":
        
        data = request.POST
        
        applicant_photo = request.FILES.get('applicant_photo')
        domicile_certificate = request.FILES.get('applicant_photo')
        income_certficate = request.FILES.get('income_certficate')
        caste_certificate = request.FILES.get('caste_certificate')
        aadhar_card = request.FILES.get('aadhar_card')
        bonafide = request.FILES.get('bonafide')
        fee_receipt = request.FILES.get('fee_receipt')
        passbook = request.FILES.get('passbook')
        
        institute_state = data.get('institute_state')
        institute_name = data.get('institute_name')
        
        applicant_name = data.get('applicant_name')
        father_name = data.get('father_name')
        mother_name = data.get('mother_name')
        gender = data.get('gender')
        annual_income = data.get('annual_income')
        category = data.get('category')
        religion = data.get('religion')
        course = data.get('course')
        enrollment = data.get('enrollment')
        adm_year = data.get('adm_year')
        pr_year = data.get('pr_year')
        mode = data.get('mode')
        pre_board = data.get('pre_board')
        prev_class = data.get('prev_class')
        pass_year = data.get('pass_year')
        disabled = data.get('disabled')
        parents_profession = data.get('parents_profession')
        acc_no = data.get('acc_no')
        ifsc = data.get('ifsc')
        
        student = Student.objects.create(
            
            applicant_name = applicant_name,
            father_name = father_name,
            mother_name = mother_name,
            gender = gender,
            annual_income = annual_income,
            category = category,
            religion = religion,
            course = course,
            enrollment = enrollment,
            adm_year = adm_year,
            pr_year = pr_year,
            mode = mode,
            pre_board = pre_board,
            prev_class = prev_class,
            pass_year = pass_year,
            disabled = disabled,
            parents_profession = parents_profession,
            acc_no = acc_no,
            ifsc = ifsc,
            
            institute_name = institute_name,
            
            applicant_photo = applicant_photo,
            domicile_certificate = domicile_certificate,
            income_certficate = income_certficate,
            caste_certificate = caste_certificate,
            aadhar_card = aadhar_card,
            bonafide = bonafide,
            fee_receipt = fee_receipt,
            passbook = passbook,
        )

        
        

    



def student_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            print('working')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            print('working')
            if user is not None:
                login(request, user)
                print('login working')
                print(user.user_type)
                if user.user_type == 1:
                    print(' a student logged in')
                    return HttpResponseRedirect(reverse('scholar:dashboard'))

            else:
                messages.error(request, 'Invalid username or password.')

    else:
        form = AuthenticationForm()

    return render(request, 'users/login.html', {'form': form})



def student_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:student_login'))

project/templates/users/dashboard.html
{% extends 'base.html' %}

{% block start %}
    <h2>Welcome {{request.user}}</h2>
    <p> Welcome to the Dashboard.</p>
    <p> You are here it means the authentication worked !!!</p>
{% endblock %}

project/templates/users/login.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block start %}



<section class="bg-gray-50  bg-gradient-to-t from-green-300 via-transparent to-orange-300">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
     

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {% if message.tags %}{{ message }}{% endif %}
    </div> 
    {% endfor %}
    {% endif %}

      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
                  Sign in to your account
              </h1>
              <form class="space-y-4 md:space-y-6" action="#" method="POST">
                  {% csrf_token %}
                  <div>
                      {{form.username | as_crispy_field}}
                      {{form.username.errors}}
                  </div>
                  <div>
                     {{ form.password | as_crispy_field }}
                      {{form.password.errors}}
                  </div>
                  <div class="flex items-center justify-between">
                      <div class="flex items-start">
                          <div class="flex items-center h-5">
                            <input id="remember" aria-describedby="remember" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
                          </div>
                          <div class="ml-3 text-sm">
                            <label for="remember" class="text-gray-500 dark:text-gray-300">Remember me</label>
                          </div>
                      </div>
                      <a href="#" class="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Forgot password?</a>
                  </div>
                  <button type="submit" class="w-full text-white  bg-blue-600 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center  ">Sign in</button>
                  <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                      Don’t have an account yet? <a href="{% url 'users:register_student' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>
{% endblock start %}

project/templates/users/register.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block start %}

<section class="vh-100" style="background-color: #eee;">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {% if message.tags %}{{ message }}{% endif %}
      </div> 
    {% endfor %}
  {% endif %}
  <div class="container-fluid h-100 ">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5 bg-gradient-to-t from-green-300 via-transparent to-orange-300 rounded-4">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form class="mx-1 mx-md-4" action="" method="POST">
                  {% csrf_token %}

                  <div class="row">
                    <!-- Column 1: CustomUser Form -->
                    <div class="col-md-6 px-5 py-1">
                      {{ user_form.first_name | as_crispy_field }}
                      
                      {{ user_form.username | as_crispy_field }}
                     
                      {{ user_form.password | as_crispy_field }}
                      {{ user_form.password2 | as_crispy_field }}
                      <!-- Add other CustomUser fields here -->
                    </div>
                    
                    <!-- Column 2: Student Form -->
                    <div class="col-md-6 px-5">
                      {{ user_form.last_name | as_crispy_field }}
                      {{ user_form.email | as_crispy_field }}
                      {{ student_form.enrollment_no | as_crispy_field }}
                      {{ student_form.course | as_crispy_field }}
                      {{ student_form.institute | as_crispy_field }}
                      <!-- Add other Student fields here -->
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Register</button>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <p>Already registered?  </p> 
                    <a href="{% url 'users:student_login' %}" class='text-blue-400'> Login</a>
                  </div>

                  
                </form>

              </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock start %}

project/templates/users/registration_success.html
{% extends 'base.html' %}

{% block content %}
    <h2> Student Registration Successfull!! </h2>
{% endblock %}
```

project/templates/users/student_regis.html
{% comment %} <!DOCTYPE html> {% endcomment %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Application</title>
    <script src="application_script.js"></script>
    <link rel="stylesheet" href="application_style.css">
    
  </head> 
  <body>
    <div>
      <header>
          <img id="logo_left" src="logo.png" alt="Logo" />
          <img id="logo_right" src="mortar_head.jpeg" alt="Logo" />
      </header>
  
      <div class="red-bar"></div>
    </div>

    <div>
      <div class="form-container">
        <form>
          <label for="Domicile">Domicile State:<span id="required">*</span></label>
          <select id="Domicile" name="domicile">
            <!-- <option value="none" selected></option> -->
            <option value="Bihar">Bihar</option>
            <option value="Delhi">Delhi</option>
            <option value="Haryana">Haryana</option>
            <option value="Rajasthan">Rajasthan</option>
            <option value="Uttar Pradesh">Uttar Pradesh</option>
          </select>
          
          <label for="institute
          ">Institute State:<span id="required">*</span></label>
          <select id="institute" name="institute_state">
            <!-- <option value="none" selected></option> -->
            <option value="Bihar">Bihar</option>
            <option value="Delhi">Delhi</option>
            <option value="Haryana">Haryana</option>
            <option value="Rajasthan">Rajasthan</option>
            <option value="Uttar Pradesh">Uttar Pradesh</option>
          </select>
          
          <label for="institute_name">Institute Name:<span id="required">*</span></label>
          <select id="institute_name" name="institute_name">
            <option value="option1">Option 1</option>
          </select>
          
          <label for="institute_code">Institute Code:<span id="required">*</span></label>
          <input type="text" id="input" name="institute_code" required />
          
          <label for="Scholarship Category">Scholarship Category:<span id="required">*</span></label>
          <select id="Scholarship Category" name="Scholarship Category">
            <option value="Pre-Metric">Pre-Metric</option>
            <option value="Post-Metric">Post-Metric</option>
          </select>
          
          <label for="dob">Date of Birth:<span id="required">*</span></label>
          <input type="date" id="input1" name="dob" required />
          
          <label for="father_name">Father Name:<span id="required">*</span></label>
          <input type="father_name" id="input2" name="father_name" id="textInput" oninput="handleInput(this)" required />
          
          <label for="Mother Name">Mother Name:<span id="required">*</span></label>
          <input type="text" id="input3" name="mother_name" id="textInput" oninput="handleInput(this)" required />
          
          <label for="annual_income">Annual Income:<span id="required">*</span></label>
          <input type="number" id="input" name="annual_income" required />
          
          <label for="gender">Gender:<span id="required">*</span></label>
          <select id="gender" name="gender">
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
          </select>
          
          <label for="category">Category:<span id="required">*</span></label>
          <select id="category" name="category">
            <option value="general">General</option>
            <option value="obc">OBC</option>
            <option value="sc">SC</option>
            <option value="st">ST</option>
          </select>
          
          <label for="religion">Religion:<span id="required">*</span></label>
          <select id="religion" name="religion">
            <option value="Hindu">Hindu</option>
            <option value="muslim">Muslim</option>
            <option value="christian">Christian</option>
            <option value="sikh">Sikh</option>
          </select>
          
          <label for="course">Course:<span id="required">*</span></label>
          <select id="course" name="course">
            <option value="bca">BCA</option>
            <option value="b.tech">B.Tech</option>
            <option value="bba">BBA</option>
          </select>
          
          <label for="enrollment">Enrollment No:<span id="required">*</span></label>
          <input type="text" id="input" name="enrollment" required />
          
          <label for="adm_year">Admission Year:<span id="required">*</span></label>
          <input type="number" id="input" name="adm_year" required />
          
          <label for="pr_year">Present Year:<span id="required">*</span></label>
          <select id="select5" name="pr_year">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
        </select>
        
        <label for="mode">Mode of Study:<span id="required">*</span></label>
        <select id="select5" name="mode">
          <option value="regular">Regular</option>
          <option value="correspondence">Correspondence</option>
        </select>
        
        <label for="pre_board">Previous Board:<span id="required">*</span></label>
        <select name="pre_board">
          <option value="cbse">CBSE</option>
          <option value="icse">ICSE</option>
          <option value="bihar_bd">Bihar Board</option>
          <option value="delhi_bd">Delhi Board</option>
          <option value="haryana_bd">Haryana Board</option>
          <option value="rajasthan_bd">Rajasthan Board</option>
          <option value="up_bd">UP Board</option>
        </select>
        
        
        <label for="prev_class">Previous Class:<span id="required">*</span></label>
        <input type="number" name="prev_class" required />
        
        <label for="pass_year">Passing Year:<span id="required">*</span></label>
        <input type="number" name="pass_year" required />
        
        <label for="percentage">Percentage:<span id="required">*</span></label>
        <input type="number" id="input" name="annual_income" min required />
        
        <label for="disabled">Disabled:<span id="required">*</span></label>
        <select id="disables" name="disabled">
          <option value="no">NO</option>
          <option value="yes">YES</option>
        </select>
        
        <label for="parents_profession">Parents Profession <span id="required">*</span></label>
        <input type="text"  name="parents_profession" required>
        
        
        <label for="acc_no">Bank Account number: <span id="required">*</span></label>
        <input type="number"  name="acc_no" required> 
        
        <label for="ifsc">IFSC Code: <span id="required">*</span></label>
          <input type="text"  name="ifsc" required> 

        <!-- <label for="select5">Select 5:</label>
          <select id="select5" name="select5">
            <option value="option1">Option 1</option>
            <option value="option2">Option 2</option>
            <option value="option3">Option 3</option>
          </select>
          
          <label for=""></label>
          <input type=""  name="" required> -->
          <span class="btn">
            <button type="submit">Submit</button>
          </span>
        </form>
      </div>
    </div>
    </body>
    </html>
    